export const ALL_TODO_REQUEST = "ALL_TODO_REQUEST";
export const ALL_TODO_SUCCESS = "ALL_TODO_SUCCESS";
export const ALL_TODO_FAIL = "ALL_TODO_FAIL";

export const ALL_COMPLETE_TODO_REQUEST = "ALL_COMPLETE_TODO_REQUEST";
export const ALL_COMPLETE_TODO_SUCCESS = "ALL_COMPLETE_TODO_SUCCESS";
export const ALL_COMPLETE_TODO_FAIL = "ALL_COMPLETE_TODO_FAIL";

export const UPDATE_TODO_REQUEST = "UPDATE_TODO_REQUEST";
export const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS";
export const UPDATE_TODO_FAIL = "UPDATE_TODO_FAIL";

export const NEW_TODO_REQUEST = "NEW_TODO_REQUEST";
export const NEW_TODO_SUCCESS = "NEW_TODO_SUCCESS";
export const NEW_TODO_FAIL = "NEW_TODO_FAIL";

export const DELETE_TODO_REQUEST = "DELETE_TODO_REQUEST";
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export const DELETE_TODO_FAIL = "DELETE_TODO_FAIL";

export const RESET_TODO_REQUEST = "RESET_TODO_REQUEST";
export const RESET_TODO_SUCCESS = "RESET_TODO_SUCCESS";
export const RESET_TODO_FAIL = "RESET_TODO_FAIL";